# Exchange settings
exchange: binance  # Replace with your exchange name
symbol: BTC/USDT
timeframe: 1h

# Model parameters
look_back: 24  # Number of periods to look back for prediction

# API credentials (if required)
api_key: YOUR_API_KEY_HERE
api_secret: YOUR_API_SECRET_HERE

# Other settings
data_start_date: 2023-01-01
data_end_date: 2023-12-31