name: Deploy MkDocs
on:
  push:
    branches:
      - main  # Set this to your default branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
      - name: Deploy
        run: mkdocs gh-deploy --force