name: Deploy MkDocs
on:
  push:
    branches:
      - main  # Set this to your default branch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-gh-deploy
      - run: mkdocs gh-deploy --force